name: Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: tdlib
        run: |
          mkdir libs
          id=$(docker create wcsiu/tdlib:1.8.0)
          docker cp $id:/td/build/libtdjson.so.1.8.0 ./libs/
          docker cp -L $id:/td/build/libtdjson.so ./libs/
          docker rm -v $id

      - name: tests
        env:
          RUSTFLAGS: "-C link-args=-Wl,-rpath,./libs,-L./libs"
        run: cargo test